version: '3.8'
services:
  # elastic search node 1
  es01:
    build:
      context: .
      args:
        ELK_VERSION: 7.15.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-local-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - my-network

  # elastic search node 2
  es02:
    build:
      context: .
      args:
        ELK_VERSION: 7.15.2
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-local-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - my-network

  # elastic search node 3
  es03:
    build:
      context: .
      args:
        ELK_VERSION: 7.15.2
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-local-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    networks:
      - my-network

  # Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - my-network

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  my-network:
    name: elasticsearch-network