version: '3.9'
services:
  grafana:
    image: grafana/grafana:latest
    user: "root"
    environment:
      - GF_SECURITY_ADMIN_USER=BrianDYKim
      - GF_SECURITY_ADMIN_PASSWORD=brian
      - GF_INSTALL_PLUGINS=redis-datasource
    restart: always
    ports:
      - 3000:3000

  redis:
    container_name: redis
    image: redis:6.2.3
    command: redis-server /etc/redis.conf
    volumes:
      - ./redis.conf:/etc/redis.conf
    restart: always
    ports:
      - 6379:6379

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  redis-exporter:
    image: oliver006/redis_exporter
    ports:
      - 9121:9121
    restart: unless-stopped
    environment:
      REDIS_ADDR: "redis:6379"
    depends_on:
      - redis
      - prometheus